// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace QpxExpress.Data
{

    // TripDestination
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class TripDestination
    {
        public int Id { get; set; } // Id (Primary key)
        public int? CountryId { get; set; } // CountryId
        public string Name { get; set; } // Name (length: 100)
        public string Code { get; set; } // Code (length: 10)
        public string Airline { get; set; } // Airline (length: 10)
        public bool BusinessClass { get; set; } // BusinessClass
        public byte Connections { get; set; } // Connections
        public byte? DepartureDay { get; set; } // DepartureDay
        public byte? ArrivalDay { get; set; } // ArrivalDay
        public System.DateTime? UpdatedOn { get; set; } // UpdatedOn

        // Reverse navigation

        /// <summary>
        /// Child Trips where [Trip].[DestinationId] point to this entity (FK_Trip_TripDestination)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Trip> Trips { get; set; } // Trip.FK_Trip_TripDestination

        // Foreign keys

        /// <summary>
        /// Parent Country pointed by [TripDestination].([CountryId]) (FK_TripDestination_Country)
        /// </summary>
        public virtual Country Country { get; set; } // FK_TripDestination_Country

        public TripDestination()
        {
            Trips = new System.Collections.Generic.List<Trip>();
        }
    }

}
// </auto-generated>
