// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace QpxExpress.Data
{

    // Trip
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class TripConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Trip>
    {
        public TripConfiguration()
            : this("dbo")
        {
        }

        public TripConfiguration(string schema)
        {
            ToTable("Trip", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Country).HasColumnName(@"Country").HasColumnType("nvarchar").IsRequired().HasMaxLength(100);
            Property(x => x.Destination).HasColumnName(@"Destination").HasColumnType("nvarchar").IsRequired().HasMaxLength(100);
            Property(x => x.AirlineCode).HasColumnName(@"AirlineCode").HasColumnType("nvarchar").IsRequired().HasMaxLength(3);
            Property(x => x.TicketType).HasColumnName(@"TicketType").HasColumnType("nvarchar").IsRequired().HasMaxLength(10);
            Property(x => x.Period).HasColumnName(@"Period").HasColumnType("date").IsRequired();
            Property(x => x.Fare).HasColumnName(@"Fare").HasColumnType("float").IsRequired();
            Property(x => x.CountryId).HasColumnName(@"CountryId").HasColumnType("int").IsOptional();
            Property(x => x.DestinationId).HasColumnName(@"DestinationId").HasColumnType("int").IsOptional();
        }
    }

}
// </auto-generated>
