// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace QpxExpress.Data
{

    // Trip
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class Trip
    {
        public int Id { get; set; } // Id (Primary key)
        public int DestinationId { get; set; } // DestinationId
        public string TicketType { get; set; } // TicketType (length: 10)
        public System.DateTime Period { get; set; } // Period
        public double Fare { get; set; } // Fare
        public bool BusinessClass { get; set; } // BusinessClass

        // Foreign keys

        /// <summary>
        /// Parent TripDestination pointed by [Trip].([DestinationId]) (FK_Trip_TripDestination)
        /// </summary>
        public virtual TripDestination TripDestination { get; set; } // FK_Trip_TripDestination
    }

}
// </auto-generated>
