// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace QpxExpress.Data
{

    // TripOld
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class TripOld
    {
        public int Id { get; set; } // Id (Primary key)
        public int DestinationId { get; set; } // DestinationId (Primary key)
        public string TicketType { get; set; } // TicketType (Primary key) (length: 10)
        public System.DateTime Period { get; set; } // Period (Primary key)
        public double Fare { get; set; } // Fare (Primary key)
        public bool BusinessClass { get; set; } // BusinessClass (Primary key)
    }

}
// </auto-generated>
