// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace QpxExpress.Data
{

    // vw_RemainingTrips
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class VwRemainingTrip
    {
        public int Id { get; set; } // Id (Primary key)
        public string Country { get; set; } // Country (Primary key) (length: 100)
        public string Name { get; set; } // Name (Primary key) (length: 100)
        public string Code { get; set; } // Code (Primary key) (length: 10)
        public string Airline { get; set; } // Airline (Primary key) (length: 3)
    }

}
// </auto-generated>
